### ISSUE TITLE
Apps tab won't load on WebUI

### ISSUE THREAD

**Issue by HGW39** [raspiblitz/raspiblitz#3608]
Upon logging in to the Web UI the Apps tab won't load, just gets stuck in continual loop. Have tried in both Brave and Firefox and same issue occurs. Noticed some other users experiencing this in the Telegram so have raised issue. Please let me know if I can help with any further testing.

<img width="1269" alt="Screenshot 2023-01-14 at 9 11 13 PM" src="https://user-images.githubusercontent.com/121190315/212462826-14ede74c-e542-4611-a093-b7ebcfa49a5b.png">

**Comment by rootzoll** [comment]
Is this still with the release candidate testversion v1.9.0rc1 or still with v1.8.0?

**Comment by HGW39** [comment]
I'm running v1.8.0
![Screenshot 2023-01-15 at 3 19 19 PM](https://user-images.githubusercontent.com/121190315/212519629-beaf715f-7755-484a-b9f6-30baa9c6c1d0.png)

**Comment by rootzoll** [comment]
We already fixed a lot on the WebUI/API side .. please try if the sd card update with Release Candidate v1.9.0rc1 already fixes your problem: https://github.com/rootzoll/raspiblitz/tree/v1.9#downloading-the-software

**Comment by HGW39** [comment]
Will do and let you know if issue persists.

**Comment by TheLuvCBD** [comment]
I'm on version 1.10.0 and I'm having the same problem. It's persisted for a few days now. I've rebooted but it's the same.

**Comment by fusion44** [comment]
@TheLuvCBD can you log in to your RaspiBlitz and take a look at the blitz API logs? Looking for any errors in there. Thank you.

sudo journalctl -f blitzapi

**Comment by barthaare** [comment]
I'm on version 1.11.0 and I'm having the same problem.

**Comment by barthaare** [comment]
`sudo journalctl -f blitzapi` results in `Failed to add match 'blitzapi': Invalid argument`

**Comment by rootzoll** [comment]
There are other issues reporting similar problems - listing here to be tested/closed if fixed:
- #4631
- #4569
- #4743

**Comment by rootzoll** [comment]
Could be fixed by https://github.com/fusion44/blitz_api/pull/272

**Comment by rootzoll** [comment]
reopen for v1.12.0 because a new report says it still happens with latest v1.11.4:
https://github.com/raspiblitz/raspiblitz/issues/4914#issuecomment-2571260464

**Comment by woiwoiwoiwoi** [comment]
Not sure if metoos help here, but I'm getting the same. 1.11.4 on Debian VM. Set up that VM specifically to tinker with Alby Hub, but can't even get there.

**Comment by geco91** [comment]
@fusion44 please make a catch all exception in that place of the api and coordinate a way with @cstenglein how to give back an error that can be displayed to the user for report.

**Comment by scarolan** [comment]
Same issue here, my home and apps tabs both just do this:

RaspiBlitz 1.11.4-fbcd2b83

![Image](https://github.com/user-attachments/assets/aef9e130-962c-4af3-9e11-84912a0bc318)

**Comment by fusion44** [comment]
Hey guys, next version will contain a substantial rework of the apps part of the backend. I hope that this problem is solved with the update.

**Comment by tulku** [comment]
Hi! Before opening a new issue, just wanted to say that I have the same situation on RaspiBlitz 1.12.0-dev
When this happens, I also notice that icons for installed apps that appeared on the side bar do not appear any longer.

**Comment by rootzoll** [comment]
@tulku Please run SSHMENU > UPDATE > PATCH and restart and let me know if the problem still persists - best would be then to run command "debug" and paste the results here

**Comment by tulku** [comment]
@rootzoll I patched the system some days ago, and the problem still persists.
Here is the debug information: https://termbin.com/ra1y

**Comment by rootzoll** [comment]
Also saw it again on v1.12.0 when there is just Bitcoin. When I install LND the Apps work again.
@fusion44 I tested wit the latest comited API
