### ISSUE TITLE
tail: cannot open '/mnt/hdd/bitcoin/debug.log' for reading: No such file or directory as per #4003

### ISSUE THREAD

**Issue by gerryb** [raspiblitz/raspiblitz#5148]
Recurrence of this issue upgrading  RaspiBlitz 1.12.0-7db2
tail: cannot open '/mnt/hdd/app-storage/bitcoin/debug.log' for reading: No such file or directory

So cannot run mempool and probably more:
App status script execution failed. ├╴at /home/blitzapi/blitz_api/app/apps/impl/raspiblitz.py:95:10 ├╴script_name: /home/admin/config.scripts/bonus.btc-rpc-explorer.sh status ├╴script_output: (Sensitive data omitted) │ ╰─▶ 500: stderr: tail: cannot open '/mnt/hdd/app-storage/bitcoin/debug.log' for reading: No such file or directory │tail: cannot open '/mnt/hdd/app-storage/bitcoin/debug.log' for reading: No such file or directory │ │---------------------------- │stdout: version='' │fatpack=1 │configured=1 │installed=1

Running bitcoin.check.sh  has no effect.

**Comment by mischalight** [comment]
I have exactly the same problem. At first time I installed raspiblitz for booting from the new internal ssd. After that error, I installed the system new for booting from micro-SD, but the same error occurs. Mempool and BTC RPC Explorer can't be installed. Electrs can and works.

I found a temporal solution for this problem: https://github.com/raspiblitz/raspiblitz/issues/5140

**Comment by gerryb** [comment]
I updated for the same reason to enable boot from Nvme drive.   The update moved partitions accordingly which took ages   But after the update Blitz does not boot from Nvme.  I have not looked further into that and shall make another ticket issue if others have not done so.

**Comment by rootzoll** [comment]
OK I merged #5156 into v1.12 branch .. please run `SSHMENU > UPDATE > PATCH` & restart and let me know if that fixes this issue.

**Comment by gerryb** [comment]
Thank you Rootzoll.  And thank you for your work on this project.

 

The error message cannot open '/mnt/hdd/bitcoin/debug.log' has gone after applying the patch

 

Installing mempool that error no longer came up, but the installation still failed and it has vanished as an available or activated app on the main raspiblitz main webpage.  Installing membool via SSH fails, suggesting using the used the bonus.mempool.sh   Yet I can reach a membool page via my  .onion address!

 

Since the patching, on booting up and looking at the console screen, the very last line before the tty screen opens there is a new red fail line.  Too fast for me to read.

 

Backup, that is creating a raspiblitz……..tar.gz,  still fails (nothing in the file) and I can read as it the creation runs red  “no migration file found”

 

All else is working well.

 

Gerry

**Comment by rootzoll** [comment]
should be fixed: please run SSHMENU > UPDATE > PATCH & restart
